# Generated by Django 4.0.5 on 2022-09-14 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_student', models.BooleanField(default=False)),
                ('is_chairman', models.BooleanField(default=False)),
                ('email_validation', models.BooleanField(default=False)),
                ('new_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('new_email_validation', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('department', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('hall', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=20)),
                ('first_semester', models.CharField(max_length=5)),
                ('second_semester', models.CharField(max_length=5)),
                ('third_semester', models.CharField(max_length=5)),
                ('fourth_semester', models.CharField(max_length=5)),
                ('fifth_semester', models.CharField(max_length=5)),
                ('sixth_semester', models.CharField(max_length=5)),
                ('seventh_semester', models.CharField(max_length=5)),
                ('eighth_semester', models.CharField(max_length=5)),
                ('total_credit_completed', models.CharField(max_length=5)),
                ('cgpa', models.CharField(max_length=5)),
                ('student_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_result', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='provost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provost_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('chairman_status', models.CharField(max_length=20)),
                ('provost_status', models.CharField(max_length=20)),
                ('librarian_status', models.CharField(max_length=20)),
                ('examController_status', models.CharField(max_length=20)),
                ('checkedBy', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_result_certificate', to='base.studentresult')),
                ('student_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info_global', to='base.student')),
            ],
        ),
        migrations.CreateModel(
            name='librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('librarian_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarian', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairman_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chairman', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
