# Generated by Django 4.0.5 on 2022-09-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='chairman_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='examController_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='librarian_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='provost_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='takeBy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
