# Generated by Django 4.0.5 on 2022-09-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_provisionalcertificate_chairman_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='chairman_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='examController_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='librarian_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='provost_approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
