# Generated by Django 4.0.5 on 2022-09-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_provisionalcertificate_chairman_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='chairman_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='checkedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='examController_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='librarian_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='provost_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
