# Generated by Django 4.0.5 on 2022-09-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionalcertificate',
            old_name='chairman_approved_date',
            new_name='chairman_action_date',
        ),
        migrations.RenameField(
            model_name='provisionalcertificate',
            old_name='examController_approved_date',
            new_name='examController_action_date',
        ),
        migrations.RenameField(
            model_name='provisionalcertificate',
            old_name='librarian_approved_date',
            new_name='librarian_action_date',
        ),
        migrations.RenameField(
            model_name='provisionalcertificate',
            old_name='provost_approved_date',
            new_name='provost_action_date',
        ),
    ]
