# Generated by Django 4.0.5 on 2022-09-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_chairman_approved_date_provisionalcertificate_chairman_action_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
