# Generated by Django 4.0.5 on 2022-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_user_new_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passing_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
