# Generated by Django 4.0.5 on 2022-09-17 02:13

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_student_passing_year_student_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='ssc_certificate',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_path),
        ),
    ]
