# Generated by Django 4.0.5 on 2022-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_testtable_arialfont_testtable_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='provisional_certificate_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
