# Generated by Django 4.0.5 on 2022-09-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_provisionalcertificate_provisional_certificate_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionalcertificate',
            name='provisional_certificate_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
