# Generated by Django 4.0.5 on 2022-09-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_provisionalcertificate_provisional_certificate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_examController',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_provost',
            field=models.BooleanField(default=False),
        ),
    ]
