# Generated by Django 4.0.5 on 2022-09-19 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_is_examcontroller_user_is_librarian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_controller_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_controller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
