# Generated by Django 4.0.5 on 2022-09-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_user_is_courier_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='courier_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisionalcertificate',
            name='courier_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
