# Generated by Django 4.0.5 on 2022-09-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_provisionalcertificate_courier_action_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='courier_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
