# Generated by Django 4.0.5 on 2022-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_provisionalcertificate_courier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionalcertificate',
            name='courier_delivery_place',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
