export const LOADING_START = "LOADING_START"

export const CHAIRMAN_USER_LOADED = "CHAIRMAN_USER_LOADED"
export const CHAIRMAN_USER_FAILED = "CHAIRMAN_USER_FAILED"

export const STUDENT_USER_LOADED = "STUDENT_USER_LOADED"
export const STUDENT_USER_FAILED = "STUDENT_USER_FAILED"

export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT_FAILED = "LOGOUT_FAILED"

export const REGISTER_STUDENT_USER_SUCCESS = "REGISTER_STUDENT_USER_SUCCESS"
export const REGISTER_STUDENT_USER_FAILED = "REGISTER_STUDENT_USER_FAILED"

export const REGISTER_CHAIRMAN_USER_SUCCESS = "REGISTER_CHAIRMAN_USER_SUCCESS"
export const REGISTER_CHAIRMAN_USER_FAILED = "REGISTER_CHAIRMAN_USER_FAILED"



export const CONTINUOUS_USER_AUTH_SUCCESS = "CONTINUOUS_USER_AUTH_SUCCESS"
export const CONTINUOUS_USER_AUTH_FAILED = "CONTINUOUS_USER_AUTH_FAILED"

export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const EMAIL_CHANGE_REQUEST_SUCCESS = "EMAIL_CHANGE_REQUEST_SUCCESS"
export const EMAIL_CHANGE_REQUEST_FAILED = "EMAIL_CHANGE_REQUEST_FAILED"

export const PASSWORD_CHANGE_REQUEST_SUCCESS = "PASSWORD_CHANGE_REQUEST_SUCCESS"
export const PASSWORD_CHANGE_REQUEST_FAILED = "PASSWORD_CHANGE_REQUEST_FAILED"

export const PASSWORD_CHANGE_CONFIRM_REQUEST_SUCCESS = "PASSWORD_CHANGE_CONFIRM_REQUEST_SUCCESS"
export const PASSWORD_CHANGE_CONFIRM_REQUEST_FAILED = "PASSWORD_CHANGE_CONFIRM_REQUEST_FAILED"

export const PROVISIONAL_CONFIRM_CHAIRMAN_SUCCESS = "PROVISIONAL_CONFIRM_CHAIRMAN_SUCCESS"

export const PROVISIONAL_CONFIRM_CHAIRMAN_FAILED = "PROVISIONAL_APPLIED_LIST_FOR_CHAIRMAN_FAILED"

export const PROVISIONAL_REJECT_CHAIRMAN_SUCCESS = "PROVISIONAL_CONFIRM_CHAIRMAN_SUCCESS"

export const PROVISIONAL_REJECT_CHAIRMAN_FAILED = "PROVISIONAL_APPLIED_LIST_FOR_CHAIRMAN_FAILED"

export const STUDENT_UPLOAD_SSC_SUCCESS = "STUDENT_UPLOAD_SSC_SUCCESS"
export const STUDENT_UPLOAD_SSC_FAILED = "STUDENT_UPLOAD_SSC_FAILED"